version: '3'

services:
  postgres:
    image: postgres:16
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: passphrase
      POSTGRES_DB: bank
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  application:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8080:8080"

volumes:
  postgres_data: