spring:
  application:
    name: random-bank

  datasource:
    url: jdbc:postgresql://postgres:5432/bank
    username: test
    password: passphrase

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


